app = "nova-khvylia"
primary_region = "ams" # Переконайся, що регіон правильний (waw або ams)
swap_size_mb = 512     # <--- ВАЖЛИВО: Це має бути тут, на самому верху!

[build]
  # Тут пусто, використовується Dockerfile

[deploy]
  release_command = "python init_db.py"

[http_service]
  internal_port = 8000
  force_https = true     # Примусовий HTTPS для безпеки (uploader.exe це підтримає)
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# Налаштування статики (CSS/JS)
[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

[processes]
  # Тайм-аут 120 секунд, щоб великий файл встиг обробитися
  app = "gunicorn --bind :8000 --workers 1 --threads 2 --timeout 120 app:app"